site_name: Hsmpp API Docs
site_url: 
pages:
- [api.md, Home]
- [message.md, /message]
- [campaign.md, /campaign]
- [user.md, /user]
- [users.md, /users]
- [file.md, /file]
- [service.md, /service]
theme: readthedocs
